plugins {
    id 'org.springframework.boot' version '3.5.16'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'java'
    id 'io.github.ben-manes.versions' version '0.64.0'
}

group = 'no.novari'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

// Starteren er kompilert mot Kotlin 2.4.10 – unngå at Spring Boot BOM nedgraderer kotlin-stdlib
ext['kotlin.version'] = '2.4.10'

jar {
    enabled = false
}

repositories {
    mavenCentral()
    maven {
        url "https://repo.fintlabs.no/releases"
    }
    mavenLocal()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation 'no.novari:flyt-gateway-starter:4.2.0'
    implementation 'org.jetbrains.kotlin:kotlin-reflect'

    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
    useJUnitPlatform()
}
