fint:
  org-id: fintlabs.no
novari:
  flyt:
    file-service-url: http://localhost:8091
    gateway-starter:
      check-integration-exists: false
  kafka:
    default-replicas: 1
    topic:
      org-id: fintlabs-no
spring:
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8103
logging:
  level:
    no.fintlabs: DEBUG
