name: CD

# This workflow is triggered on every push
# [skip ci] can be added to the commit message to skip the CI workflow
# org:<org> can be added to the commit message to deploy to a specific organisation

on: push

jobs:

  organizations-to-deploy:
    uses: ./.github/workflows/reusable-get-organizations.yaml

  build-push:
    uses: ./.github/workflows/reusable-build-push.yaml

  deploy-beta:
    needs: [ build-push, organizations-to-deploy ]
    uses: ./.github/workflows/reusable-deploy-to-aks.yaml
    with:
      cluster: aks-beta-fint-2021-11-23
      tags: ${{ needs.build-push.outputs.tags }}
      organizations: ${{ needs.organizations-to-deploy.outputs.beta }}
      deploy-every-branch: true
    secrets: inherit

  deploy-api:
    needs: [ deploy-beta, organizations-to-deploy ]
    uses: ./.github/workflows/reusable-deploy-to-aks.yaml
    with:
      cluster: aks-api-fint-2022-02-08
      tags: ${{ needs.build-push.outputs.tags }}
      organizations: ${{ needs.organizations-to-deploy.outputs.api }}
      deploy-every-branch: false
    secrets: inherit