name: CD

on: push

jobs:

  reusable-build-push:
    uses: ./.github/workflows/reusable-build-push.yaml

  reusable-deploy-to-aks:
    strategy:
      matrix:
        cluster: [ aks-beta-fint-2021-11-23 ]
    uses: ./.github/workflows/reusable-deploy-to-aks.yaml
    with:
        cluster: ${{ matrix.cluster }}
        tags: ${{ needs.reusable-build-push.outputs.tags }}