name: MD

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Select and environment'
        required: true
        default: 'warning'
        type: choice
        options:
          - aks-alpha-fint-2021-11-18
          - aks-beta-fint-2021-11-23
          - aks-api-fint-2022-02-08
      org:
        description: 'Select organisation'
        required: true
        default: 'warning'
        type: choice
        options:
          - fintlabs-no
          - vlfk-no

jobs:

  build-push:
    uses: ./.github/workflows/reusable-build-push.yaml

  deploy:
    needs: build-push
    uses: ./.github/workflows/reusable-deploy-to-aks.yaml
    with:
      cluster: ${{ inputs.cluster }}
      tags: ${{ needs.build-push.outputs.tags }}
      organizations: ${{ format('"{0}"', inputs.org) }}
      deploy-every-branch: true
    secrets: inherit
