name: Get organizations from kustomize file structure or commit message

on:
  workflow_call:
    outputs:
      beta:
        value: ${{ jobs.get-organizations.outputs.beta }}
      api:
        value: ${{ jobs.get-organizations.outputs.api }}

jobs:

  get-organizations:
    runs-on: ubuntu-latest
    outputs:
      beta: ${{ steps.generated-outputs.outputs.beta }}
      api: ${{ steps.generated-outputs.outputs.api }}
    steps:
      - uses: actions/checkout@v4

      - name: Get organizations from Kustomize
        id: organizations
        run: |
          echo "Organizations from Kustomize:" >> $GITHUB_STEP_SUMMARY
          for ENV in beta api
          do
            ORGS=$(find kustomize/overlays -name $ENV -mindepth 2 -maxdepth 2 -type d | sed 's|kustomize/overlays/\(.*\)/.*|"\1"|' | paste -sd, -) 
            echo "$ENV=[$ORGS]" >> $GITHUB_OUTPUT 
            echo "* $ENV: [$ORGS]" >> $GITHUB_STEP_SUMMARY
          done

      - name: Get organization from commit message
        id: org-from-commit
        run: |
          ORG=$(git log -1 --pretty=format:'%s' | awk '{for(i=1;i<=NF;i++) if ($i ~ /^org:/) {print substr($i,5); exit}}')
          echo "org=$ORG" >> $GITHUB_OUTPUT

      - name: Generate output
        id: generated-outputs
        run: |
          if [ -z ${{ steps.org-from-commit.outputs.org }} ] ; then
            echo "Using organizations from Kustomize file structure (no organization in commit message)." >> $GITHUB_STEP_SUMMARY
            echo "beta=${{ grep steps.organizations.outputs.beta }}" >> $GITHUB_OUTPUT
            echo "api=${{ grep steps.organizations.outputs.api }}" >> $GITHUB_OUTPUT
          else   
            echo "Using organization from commit message: $ORG" >> $GITHUB_STEP_SUMMARY
            echo "beta=${{ contains(steps.organizations.outputs.beta, steps.org-from-commit.outputs.beta) && steps.org-from-commit.outputs.org || '[]'" }}" >> $GITHUB_OUTPUT
            echo "api=${{ contains(steps.organizations.outputs.api, steps.org-from-commit.outputs.api) && steps.org-from-commit.outputs.org || '[]'" }}" >> $GITHUB_OUTPUT
          fi
