name: Build and push to GHCR

on:
  workflow_call:
    outputs:
      tags:
        value: ${{ jobs.build-and-publish.outputs.tags }}
      organizations-beta:
        value: ${{ jobs.build-and-publish.outputs.organizations-beta }}
      organizations-api:
        value: ${{ jobs.build-and-publish.outputs.organizations-api }}

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      organizations-beta: ${{ steps.organizations.outputs.beta }}
      organizations-api: ${{ steps.organizations.outputs.api }}
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v4

      - name: Get organizations
        id: organizations
        run: |
          for ENV in beta api
          do
            ORGS=$(find kustomize/overlays -name $ENV -mindepth 2 -maxdepth 2 -type d | sed 's|kustomize/overlays/\(.*\)/.*|"\1"|' | paste -sd, -)
            echo "$ENV=$ORGS" >> $GITHUB_OUTPUT 
            echo "$ENV: $ORGS" >> $GITHUB_STEP_SUMMARY
          done

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch,suffix=-{{sha}}
            type=ref,event=pr,suffix=-{{sha}}
            type=sha,prefix={{date 'YYYY-MM-DD-'}},enable={{is_default_branch}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
